CREATE TABLE links (
    id SERIAL PRIMARY KEY,
    original_url TEXT NOT NULL,
    short_code TEXT UNIQUE NOT NULL,
    clicks INTEGER NOT NULL DEFAULT 0,
    max_clicks INTEGER DEFAULT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    owner TEXT NOT NULL,
    last_accessed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
